/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jgi_BBMergeOverlapper */

#ifndef _Included_jgi_BBMergeOverlapper
#define _Included_jgi_BBMergeOverlapper
#ifdef __cplusplus
extern "C" {
#endif
#undef jgi_BBMergeOverlapper_IGNORE_MAPPING_STRAND
#define jgi_BBMergeOverlapper_IGNORE_MAPPING_STRAND 0L
/*
 * Class:     jgi_BBMergeOverlapper
 * Method:    mateByOverlapJNI
 * Signature: ([B[B[B[B[IIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_jgi_BBMergeOverlapper_mateByOverlapJNI
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jintArray, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
